AVRDDUDE     = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
BOARD_TAG    = uno
USER_CPP = ~/git/Temp/Linx/device/wiring/arduino/Sam.cpp
OBJDIR = ../../../../bin/$(BOARD_TAG)


include ~/arduino/Arduino-Makefile/Arduino.mk

