AVRDDUDE     = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf
BOARD_TAG    = uno
USER_CPP =  ../../listener/LinxListener.cpp ../../listener/LinxSerialListener.cpp ../../device/LinxDevice.cpp ../../device/wiring/arduino/uno/LinxArduinoUno.cpp ../../device/wiring/arduino/LinxArduino.cpp ../../device/wiring/LinxWiringDevice.cpp
#OBJDIR = ../../../../bin/$(BOARD_TAG)


include ~/arduino/Arduino-Makefile/Arduino.mk


#include "../../LinxCommon.h"
#include "../../device/LinxDevice.h"
#include "../../listener/LinxSerialListener.h"
